
from common import PYTHON, Pipeline, packages
from inference.backend import BackendMixin
from metaflow import (
    FlowSpec,
    Parameter,
    conda_base,
    project,
    step,
)


@project(name="penguins")
@conda_base(
    python=PYTHON,
    packages=packages("mlflow", "pandas", "numpy", "boto3", "requests"),
)
class Labels(FlowSpec, Pipeline, BackendMixin):
    """A pipeline for generating fake labels for data captured by a hosted model."""

    ground_truth_quality = Parameter(
        "ground-truth-quality",
        help=(
            "How similar the ground truth should be to the predictions generated by "
            "the model. Setting this parameter to a value less than 1.0 will introduce "
            "noise in the labels to simulate inaccurate model predictions."
        ),
        default=0.8,
        required=False,
    )

    @step
    def start(self):
        """Start the pipeline."""
        self.backend_impl = self.load_backend()
        self.next(self.generate_labels)

    @step
    def generate_labels(self):
        """Generate ground truth for unlabeled data captured by the model."""
        self.labeled_samples = self.backend_impl.label(
            self.ground_truth_quality)

        self.next(self.end)

    @step
    def end(self):
        """End of the pipeline."""
        logger = self.configure_logging()
        logger.info("Labeled %s samples.", self.labeled_samples)


if __name__ == "__main__":
    Labels()
