project: penguins

logging: logging.conf
mlflow_tracking_uri: http://127.0.0.1:5000/

backend:
  module: backend.SageMaker
  target: ${ENDPOINT_NAME}
  data-capture-uri: s3://${BUCKET}/datastore
  ground-truth-uri: s3://${BUCKET}/ground-truth
  region: ${AWS_REGION}