project: penguins

backend:
  backend: backend.SageMaker
  target: ${ENDPOINT_NAME}
  data-capture-uri: s3://${BUCKET}/datastore
  ground-truth-uri: s3://${BUCKET}/ground-truth
  region: ${AWS_REGION}